name: Build-Test

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
      - "main"

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - run: dotnet build -c Debug
      - run: dotnet build -c Release
      - run: dotnet test -c Debug --no-build
      - run: dotnet test -c Release --no-build